#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor11,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motor12,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

short numberToDisplay = 0;

task main()
{
	while(true) {
		motor[motor11] = 50;
		numberToDisplay = nMotorEncoder[motor11];
		nxtDisplayCenteredTextLine(3, "%d", numberToDisplay);
		wait10Msec(10);
		eraseDisplay();
	}
}
