#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     HTIRL,          sensorI2CCustom)
#pragma config(Sensor, S4,     HTGYRO,         sensorNone)
#pragma config(Motor,  motorA,          nxtMotorA,     tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
//#include "drivers/HTDIR-driver.h"
#include "drivers/HTGYRO-driver.h"

float Gyro_offset;           //**offset value may vary depending on sensor & temperature
long Gyro_value;             //current read
long sum;
int degrees;
//int IR_value;
//int IR_offset;

tSensors HTGYRO;


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  Gyro_offset = HTGYROstartCal(HTGYRO);   //start calibration, but do not trust results
  for (int i = 0 ; i < 20; i++)           //instead read 20 values and generate average offset
  {
    sum = sum + HTGYROreadRot(HTGYRO);
    wait1Msec(10);
  }
  Gyro_offset = sum / 20.0;

  return;
}

///////////////////////////////////////////////////////////////////////////////////////
//
//                                    Program Functions
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void moveStraight(int delay, int speed)
{
   sum = 0;
   ClearTimer(T1);
   while (time1(T1) < delay)
   {
     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
     sum = sum + Gyro_value;
     degrees = sum / 20.0;                               // current heading of robot (-CCW, +CW)
     motor[motorLeft] = speed - 5*degrees;               // Travel straight at speed
     motor[motorRight] = -speed - 5*degrees;
     wait1Msec(50);
   }
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
bool turnRight(int speed)
{
   sum = 0;
   degrees = 0;
   ClearTimer(T1);
   while (degrees < 90)             // while bearing less than 90
   {
     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
     sum = sum + Gyro_value;
     degrees = sum / 18.0;          // current heading of robot (-CCW, +CW)
     motor[motorLeft] = speed;
     motor[motorRight] = speed;
     wait1Msec(50);
     if (time1(T1) > 5000)          // try for no more than 5 seconds
     {
       motor[motorLeft] = 0;
       motor[motorRight] = 0;
       return false;
     }
   }
   return true;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
bool turnLeft(int speed)
{
   sum = 0;
   degrees = 0;
   ClearTimer(T1);
   while (degrees > -90)             // while bearing greater than -90
   {
     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
     sum = sum + Gyro_value;
     degrees = sum / 18.0;          // current heading of robot (-CCW, +CW)
     motor[motorLeft] = -speed;
     motor[motorRight] = -speed;
     wait1Msec(50);
     if (time1(T1) > 5000)          // try for no more than 5 seconds
     {
       motor[motorLeft] = 0;
       motor[motorRight] = 0;
       return false;
     }
   }
   return true;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous phase.

  moveStraight(1000, 50);
  turnRight(50);
  turnLeft(50);

/*
  while (true)
  {}
  */
}
