#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S3,     HTIRL,               sensorLowSpeed)
#pragma config(Sensor, S4,     HTGYRO,              sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     wristMotor,    tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    fingers,              tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    wrist,                tServoNormal)
#pragma config(Servo,  srvo_S1_C2_3,    tipperL,              tServoNormal)
#pragma config(Servo,  srvo_S1_C2_4,    tipperR,              tServoNormal)
#pragma config(Servo,  srvo_S1_C2_5,    trapperL,             tServoNormal)
#pragma config(Servo,  srvo_S1_C2_6,    trapperR,             tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
//#include "drivers/HTDIR-driver.h"
#include "drivers/HTGYRO-driver.h"

float Gyro_offset;           //**offset value may vary depending on sensor & temperature
long Gyro_value;             //current read
long sum;
int degrees;
int IR_value;
int IR_offset;
int wristPosition = 35;
int fingerPosition = 127;
int trapperPosition = 100;
int tipperPosition = 220;
int servoIncrement = 8;

tSensors HTGYRO;


///////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  nMotorPIDSpeedCtrl[wristMotor] = mtrSpeedReg;
  nMotorEncoder[wristMotor] = 0; //Resets Encoder Values

  //servoChangeRate[wrist] = 2;    // Slows the Change Rate of wrist to 2 positions per update.  Default = 10
  servo[wrist] = wristPosition;
  servo[fingers] = fingerPosition;
  servo[trapperL] = trapperPosition;
  servo[trapperR] = 256 - trapperPosition;
  servo[tipperL] = tipperPosition;
  servo[tipperR] = 256 - tipperPosition;

  Gyro_offset = HTGYROstartCal(HTGYRO);   //start calibration, but do not trust results
  for (int i = 0 ; i < 20; i++)           //instead read 20 values and generate average offset
  {
    sum = sum + HTGYROreadRot(HTGYRO);
    wait1Msec(10);
  }
  Gyro_offset = sum / 20.0;

  return;
}


///////////////////////////////////////////////////////////////////////////////////////
//
//                                    Program Functions
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void moveStraight(int delay, int speed)
{
   sum = 0;
   ClearTimer(T1);
   while (time1(T1) < delay)
   {
     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
     sum = sum + Gyro_value;
     degrees = sum / 20.0;                               // current heading of robot (-CCW, +CW)
     motor[leftMotor] = speed - 5*degrees;               // Travel straight at speed
     motor[rightMotor] = -speed - 5*degrees;
     wait1Msec(50);
   }
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
bool turnRight(int speed)
{
   sum = 0;
   degrees = 0;
   ClearTimer(T1);
   while (degrees < 90)             // while bearing less than 90
   {
     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
     sum = sum + Gyro_value;
     degrees = sum / 18.0;          // current heading of robot (-CCW, +CW)
     motor[leftMotor] = speed;
     motor[rightMotor] = speed;
     wait1Msec(50);
     if (time1(T1) > 5000)          // try for no more than 5 seconds
     {
       motor[leftMotor] = 0;
       motor[rightMotor] = 0;
       return false;
     }
   }
   return true;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
bool turnLeft(int speed)
{
   sum = 0;
   degrees = 0;
   ClearTimer(T1);
   while (degrees > -90)             // while bearing greater than -90
   {
     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
     sum = sum + Gyro_value;
     degrees = sum / 18.0;          // current heading of robot (-CCW, +CW)
     motor[leftMotor] = -speed;
     motor[rightMotor] = -speed;
     wait1Msec(50);
     if (time1(T1) > 5000)          // try for no more than 5 seconds
     {
       motor[leftMotor] = 0;
       motor[rightMotor] = 0;
       return false;
     }
   }
   return true;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
/*
bool travelToIR(int time)      //1 = Behind Left, 2 = Left 90, 5 = Straight Ahead,
{                              //8 = Right 90, 9 = Behind Right, -1 = No Signal
  sum = 0;
  degrees = 0;
  //ClearTimer(T1);
  //IR_value=HTDIRreadDCDir(S3);
//  while ((IR_value == 0) && (degrees < 360) && (time1(T1) < 7000))  //if IR not found, try 360 degree loop
//  {
//     Gyro_value = HTGYROreadRot(HTGYRO) - Gyro_offset;
//     sum = sum + Gyro_value;
//     degrees = sum / 18.0;          // current heading of robot (-CCW, +CW)
//     motor[leftMotor] = 30;
//     motor[rightMotor] = 30;
//     IR_value=HTDIRreadDCDir(S3);
//     wait1Msec(50);
//  }
//  if (IR_value == 0)               //still haven't found IR
//  {
//       motor[leftMotor] = 0;
//       motor[rightMotor] = 0;
//       return false;
//  }

  ClearTimer(T3);
  while (time1(T3) < time)
  {
    IR_value=HTDIRreadDCDir(S3);
    if (IR_value < 5)
    {
      motor[leftMotor] = 10;
      motor[rightMotor] = -50;
    }
    else if (IR_value > 5)
    {
      motor[leftMotor] = 50;
      motor[rightMotor] = -10;
    }
    else
    {
      motor[leftMotor] = 50;
      motor[rightMotor] = -50;
    }
    wait1Msec(50);
  }

  motor[leftMotor] = 0;
  motor[rightMotor] = 0;

  if (IR_value == 0)
    return false;
  else
    return true;
}
*/
/////////////////////////////////////////////////////////////////////////////////////////////////////
void dumpBatons()
{
  for(int i = 0; i < 3; i++)
  {
    servo[wrist] = 150;
    wait1Msec(500);
    servo[wrist] = 35;
    wait1Msec(500);
  }
  servo[wrist] = 35;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  //moveStraight(500,50);  //move stright for 500ms at 50% speed
  //turnRight(50);
  //turnLeft(50);
  //travelToIR(6000);
  dumpBatons();
}
