#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//MotorD is right motors, MotorE is left motors

task main()
{
  moveForward(4000);
}

task moveForward(int milliseconds)
{
   motor[motorRight] = 25;
   motor[motorLeft] = 25;
   wait1Msec(milliseconds);
   motor[motorRight] = 0;
   motor[motorLeft] = 0;
}
