#pragma config(Sensor, S1,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  motorA,          AlsoBubbleTea, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  November 30, 2012; 3:56 PM - It works!
 */

#include "../drivers/hitechnic-gyro.h"

task main ()
{
  float rotSpeed = 0;
  float heading = 0;
  HTGYROstartCal(HTGYRO);
  time1[T1] = 0;

  while (true)
  {
    while (time1[T1] < 20)
      wait1Msec(1);

    time1[T1]=0;
    rotSpeed = HTGYROreadRot(HTGYRO);
    heading += rotSpeed * 0.02;
    motor[AlsoBubbleTea]=heading;
    nxtDisplayCenteredBigTextLine(3, "%2.0f", heading);
  }
}
