#pragma config(Sensor, S1,     HowAboutNo,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          Thing1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Thing2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          CatintheHat,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "moardrivers/" //shit goes down

#define MAXMOTORSPEED = 100;
float currHeading = 0;

// Task to keep track of the current heading using the HT Gyro
task getHeading () {
	float delTime = 0;
	float prevHeading = 0;
	float curRate = 0;

  HTGYROstartCal(HowAboutNo);
  PlaySound(soundBeepBeep);
  while (true) {
    time1[T1] = 0;
    curRate = HTGYROreadRot(HowAboutNo);
    if (abs(curRate) > 3) {
      prevHeading = currHeading;
      currHeading = prevHeading + curRate * delTime;
      if (currHeading > 360) currHeading -= 360;
      else if (currHeading < 0) currHeading += 360;
    }
    wait1Msec(5);
    delTime = ((float)time1[T1]) / 1000;
    //delTime /= 1000;
  }
}

void MoveRobot(int angle, int Vb, int rotSpeed) {
  float Vw1, Vw2, Vw3, norm_factor;

  // Adjust the angle to make it more intuitive
  angle-=90;

  // Calculate the individual motor speeds
  Vw1 = rotSpeed + Vb * cosDegrees(angle);
  Vw2 = rotSpeed + Vb * (-0.6 * cosDegrees(angle) + 0.8 * sinDegrees(angle));
  Vw3 = (rotSpeed + Vb * (-0.6 * cosDegrees(angle) - 0.8 * sinDegrees(angle))) * -1;

  // This normalises all of the values to make sure
  // no motor value peaks over 100%
  if (Vw1 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw1;
  } else if (Vw2 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw2;
  } else if (Vw3 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw3;
  } else {
    norm_factor = 1.0;
  }

  // Power the motors.
  motor[Thing1] = Vw1 * norm_factor;
  motor[Thing2] = Vw2 * norm_factor;
  motor[CatintheHat] = Vw3 * norm_factor;
}

task main()
{
	StartTask(getHeading);
  wait1Msec(500);
	while(true) {
		MoveRobot(currHeading, 60, 70);
    wait1Msec(10);
	}
}
