#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     HTGYRO,         sensorNone)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *
 */

#include "../drivers/hitechnic-gyro.h"

task main ()
{
  float rotSpeed = 0;
  float heading = 0;
  HTGYROstartCal(HTGYRO);
  time1[T1] = 0;

  while (true)
  {
    while (time1[T1] < 20)
      wait1Msec(1);

    time1[T1]=0;
    rotSpeed = HTGYROreadRot(HTGYRO);
    heading += rotSpeed * 0.02;
    if((heading < 80) && (heading > 10))
    {
	    motor[motorD]=heading;
	    motor[motorE]=heading;
  	}
    nxtDisplayCenteredBigTextLine(3, "%2.0f", heading);
  }
}
