#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     irsensor,       sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     irsensor2,      sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,          nxtMotorA,     tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          nxtMotorB,     tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          nxtMotorB,     tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor11,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor12,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motor21,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motor22,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


short ThatWasGramaticallyCorrectIThink = 0;
short shortshortshort = 0;

task main()
{
	while(true) {
		ThatWasGramaticallyCorrectIThink = SensorValue[S3];
		shortshortshort = SensorValue[S4];
		nxtDisplayCenteredTextLine(3, "%d", ThatWasGramaticallyCorrectIThink);
		nxtDisplayCenteredTextLine(4, "%d", shortshortshort);
		wait10Msec(10);
		eraseDisplay();
	}
}
