#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     irsensor,       sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     irsensor2,      sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,          nxtMotorA,     tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          nxtMotorB,     tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          nxtMotorB,     tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor11,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor12,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motor21,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motor22,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../Headers/CSEnumerated.h"
#include "../Headers/CSGlobalVariables.h"
#include "../Headers/CSMethods.h"
#include "../Drivers/HTIRS2-driver.h"

short ThatWasGramaticallyCorrectIThink = 0;
short shortshortshort = 0;

task main()
{
	HTIRS2setDSPMode(irsensor, DSP_1200);
	HTIRS2setDSPMode(irsensor2, DSP_1200);
	while(true) {
  	int irArray[5];
  	int irArray2[5];
  	HTIRS2readAllACStrength(irsensor, irArray[0], irArray[1], irArray[2], irArray[3], irArray[4]);
  	HTIRS2readAllACStrength(irsensor2, irArray2[0], irArray2[1], irArray2[2], irArray2[3], irArray2[4]);

  	int p = (irArray[1]-irArray[2])-10;
  	writeDebugStream("(%d) ",p);
  	for (int i = p+20; i > 0;i-=2){
  		writeDebugStream("#");
  	}
	}
}
