#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     touchMuxer,     sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motor12,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motor11,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor21,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motor22,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")

#include "JoystickDriver.c"
#include "../Headers/CSEnumerated.h"
#include "../Headers/CSMethods.h"

void initializeRobot() { return; }

task main() {
	int currentLight = SensorValue(lightSensor);
	while (true) {
		currentLight = SensorValue(lightSensor);
		if (currentLight < lightSensorThreshold) { //-5) || (currentLight > lightSensorThreshold+5)) {
			if (lightStrafeCount % 2 == 1) {
				motorStrafeForDistance(autonomousWheelPower, lightFineAdjust);
				//lightStrafeCount++;
				wait10Msec(lightDelay);
			}
			else if (lightStrafeCount % 2 == 0) {
				motorStrafeForDistance(-autonomousWheelPower, lightFineAdjust);
				//lightStrafeCount++;
				wait10Msec(lightDelay);
			}
		}
		else {
			motorForDistance(autonomousWheelPower, lightFineAdjust);
			//lightStrafeCount = 1;
			wait10Msec(lightDelay);
		}
	}
}
