#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     armTop,         sensorTouch)
#pragma config(Sensor, S3,     armBottom,      sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor11,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motor12,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorArm2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motor21,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motor22,       tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")

#include "JoystickDriver.c"
#include "../Headers/CSEnumerated.h"
#include "../Headers/CSMethods.h"

int controllerAMultiplier = 1;

void initializeRobot() { return; }

void processWheels() {
	/*
	if (Button(CONTROLLER_A, 2) && Button(CONTROLLER_A, 8))
		controllerAMultiplier = -0.5;
	else if (Button(CONTROLLER_A, 8) && !Button(CONTROLLER_A, 2))
		controllerAMultiplier = -1;
	else if (Button(CONTROLLER_A, 2) && !Button(CONTROLLER_A, 8))
		controllerAMultiplier = 0.5;
	else
		controllerAMultiplier = 1;
	*/

	if (Button(CONTROLLER_A, 8))
		controllerAMultiplier = -1;
	else
		controllerAMultiplier = 1;

	if (((Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X) > 15) || (Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X) < -15)) && !Button(CONTROLLER_A, 7)) {
		MotorF(motor11, Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier);
		MotorF(motor21, Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier);
	}
	else if (!Button(CONTROLLER_A, 5) && !Button(CONTROLLER_A, 6) && (Hat(CONTROLLER_A) == HAT_NONE)) {
		MotorS(motor11);
		MotorS(motor21);
	}

	if ((Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) > 15) || (Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) < -15)) {
		MotorF(motor12, Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y)*controllerAMultiplier);
		MotorF(motor22, Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y)*controllerAMultiplier);
	}
	else if (!Button(CONTROLLER_A, 5) && !Button(CONTROLLER_A, 6) && (Hat(CONTROLLER_A) == HAT_NONE)) {
		MotorS(motor12);
		MotorS(motor22);
	}

	if (Button(CONTROLLER_A, 3))
		specifyTwoMotorsForDistance(motor11, motor21, 25, 0.01);
	else if (Button(CONTROLLER_A, 1))
		specifyTwoMotorsForDistance(motor11, motor21, -25, 0.01);

	if (Hat(CONTROLLER_A) == HAT_NE) {
		MotorF(motor12, 90*controllerAMultiplier);
		MotorF(motor22, 90*controllerAMultiplier);
		MotorF(motor11, 90*controllerAMultiplier);
		MotorF(motor21, 90*controllerAMultiplier);
	}
	else if (Hat(CONTROLLER_A) == HAT_NW) {
		MotorF(motor12, 90*controllerAMultiplier);
		MotorF(motor22, 90*controllerAMultiplier);
		MotorF(motor11, -90*controllerAMultiplier);
		MotorF(motor21, -90*controllerAMultiplier);
	}
	else if (Hat(CONTROLLER_A) == HAT_SW) {
		MotorF(motor12, -90*controllerAMultiplier);
		MotorF(motor22, -90*controllerAMultiplier);
		MotorF(motor11, -90*controllerAMultiplier);
		MotorF(motor21, -90*controllerAMultiplier);
	}
	else if (Hat(CONTROLLER_A) == HAT_SE) {
		MotorF(motor12, -90*controllerAMultiplier);
		MotorF(motor22, -90*controllerAMultiplier);
		MotorF(motor11, 90*controllerAMultiplier);
		MotorF(motor21, 90*controllerAMultiplier);
	}

	if(Button(CONTROLLER_A, 5)) {
		if (controllerAMultiplier == -1)
			spinLeft();
		else
			spinRight();
	}
	else if(Button(CONTROLLER_A, 6)) {
		if (controllerAMultiplier == -1)
			spinRight();
		else
			spinLeft();
	}
}

void processArm() {
	if ((Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y) > 15) || (Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y) < -15)) {
		if((SensorValue(armTop) == 0) && (SensorValue(armBottom) == 0))
			MotorF(motorArm, Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2);
		else if ((SensorValue(armTop) == 1) && (Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2 < 0))
			MotorF(motorArm, Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2);
		else if ((SensorValue(armBottom) == 1) && (Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2 > 0))
			MotorF(motorArm, Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2);
		else if ((SensorValue(armTop) == 1) || (SensorValue(armBottom) == 1))
			MotorS(motorArm);
	}
	else
		MotorS(motorArm);

	if (Button(CONTROLLER_B, 4))
		ArmUpDistance(0.25);
	else if (Button(CONTROLLER_B, 2))
		ArmDownDistance(0.25);
}

void processServos() {

	//if ((Happy(CONTROLLER_B, JOYSTICK_L, AXIS_Y) > 10) || (Happy(CONTROLLER_B, JOYSTICK_L, AXIS_Y) < -10)) {
	servo[servo1] += Happy(CONTROLLER_B, JOYSTICK_L, AXIS_Y)*-0.0125;
	//}
	/*
	if(Button(CONTROLLER_A, 2)) {
	servo[servo1] += 1;,
	}
	else if(Button(CONTROLLER_A, 4)) {
	servo[servo1] += -1;
	}
	*/
}

task main() {
	initializeRobot();
	for (int i=0; ; i++) {
		CatsAndCorgis();
		processWheels();
		processArm();
		//processServos();
	}
}
