#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S3,     HTIRL,               sensorLowSpeed)
#pragma config(Sensor, S4,     HTGYRO,              sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     wristMotor,    tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    elbow,                tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    wrist,                tServoNormal)
#pragma config(Servo,  srvo_S1_C2_3,    tipperL,              tServoNormal)
#pragma config(Servo,  srvo_S1_C2_4,    tipperR,              tServoNormal)
#pragma config(Servo,  srvo_S1_C2_5,    trapperL,             tServoNormal)
#pragma config(Servo,  srvo_S1_C2_6,    trapperR,             tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../3rd Party Sensor Drivers/drivers/HTDIR-driver.h"
#include "../3rd Party Sensor Drivers/drivers/HTGYRO-driver.h"

int IR_value;
int IR_offset;
long Gyro_offset = 598;      //**offset value may vary depending on sensor & temperature
long Gyro_value;
long sum;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  Gyro_offset = HTGYROstartCal(HTGYRO);   //start calibration, but do not trust results
  for (int i = 0 ; i < 10; i++)           //instead read 10 values and generate average offset
  {
    sum = sum + HTGYROreadRot(HTGYRO);
    wait1Msec(50);
  }
  Gyro_offset = sum / 10.0;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  while (true)
  {
        PlaySound(soundBlip);                          // Play the sound, 'soundBeepBeep'.
        Gyro_value=HTGYROreadRot(HTGYRO);              //read the gyro sensor
        IR_value=HTDIRreadDCDir(S3);

        for(int i = 0; i < 200; i++)
        {
          motor[leftMotor] = 50;                         // Travel straight
          motor[rightMotor] = 50;
          wait1Msec(50);
        }

      // Wait for 2.5 seconds

        motor[leftMotor] = 0;                          // Stop
        motor[rightMotor] = 0;

        for (int i = 0; i < 200; i++)                  // Start looking for IR beacon
        {
          IR_value = HTDIRreadDCDir(S3);
          IR_offset = IR_value - 5;                    // 5 is center value
          motor[leftMotor] = 50 - 5*IR_offset;
          motor[rightMotor] = 50 + 5*IR_offset;
          wait1Msec(50);                               // Wait before looping again.
        }

        motor[leftMotor] = 0;                          // Stop
        motor[rightMotor] = 0;

        PlaySound(soundBlip);                          // Play the sound, 'soundBeepBeep'.

        while(true) {wait1Msec(1);}                    // Loop forever doing nothing
  }
}
