#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorKesi,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorDana,     tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     mororAlex,     tmotorNormal, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //le joystick things

void TeleOp()
{
	getJoystickSettings(joystick);  //get updates from joystick

  motor[motorRight] = -joystick.joy1_y2*0.5;      // motorRight's powerlevel is set to the y2 stick's current position.
  motor[motorKesi] = -joystick.joy1_y1*0.5;      // motorKesi's powerlevel is set to the y2 stick's current position.
  motor[motorDana] = joystick.joy2_y2*0.5;      // motorDana's powerlevel is set to the y2 stick's current position.
  motor[motorAlex] = joystick.joy2_y1*0.5;      // motorAlex's powerlevel is set to the y2 stick's current position.
}

task main()
{
  while (true)
  { TeleOp(); }
}
