#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          nxtMotorA,     tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          nxtMotorB,     tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorScsL,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorScsR,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorArmL,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorArmR,     tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //le joystick things
short caseyIsTall = 5; //value which is used to do stuff
//short alexLikesMenRoof = 120;
//short alexLikesMenFloor = 230;

void TeleOp() //le teleop method
// @(^.^)@ DANA'S MONKEY
{
	getJoystickSettings(joystick);  //get updates from joystick

	//wheels
	if ( abs(joystick.joy1_y2) > 15 )
    motor[motorR] = -joystick.joy1_y2*0.5;
  else
    motor[motorR] = 0;

  if ( abs(joystick.joy1_y1) > 15 )
    motor[motorL] = -joystick.joy1_y1*0.5;
  else
    motor[motorL] = 0;

	//arms
	if(joy2Btn(7) == 1) //if(joystick.joy2_TopHat == 0)
    motor[motorArmR] = 25;
  else if(joy2Btn(5) == 1) //else if(joystick.joy2_TopHat == 4)
    motor[motorArmR] = -25;
  else
    motor[motorArmR] = 0;

	if(joy2Btn(8) == 1) //if(joystick.joy2_TopHat == 2)
    motor[motorArmL] = 25;
  else if(joy2Btn(6) == 1) //else if(joystick.joy2_TopHat == 6)
    motor[motorArmL] = -25;
  else
    motor[motorArmL] = 0;

  //scissors
  /*if(joy2Btn(5) == 1)
  {
	  if ( abs(joystick.joy2_y2) > 15 )
	    motor[motorScsR] = joystick.joy2_y2;
	  else
	    motor[motorScsR] = 0;
	  if ( abs(joystick.joy2_y1) > 15 )
	    motor[motorScsL] = -joystick.joy2_y1;
	  else
	    motor[motorScsL] = 0;
  }
  else
  {*/
  if ( abs(joystick.joy2_y2) > 15 )
    motor[motorScsR] = -joystick.joy2_y2*0.4;
  else
    motor[motorScsR] = 0;

  if ( abs(joystick.joy2_y1) > 15 )
    motor[motorScsL] = -joystick.joy2_y1*0.4;
  else
    motor[motorScsL] = 0;
  /*}*/

  //arm servos
  /*
  if(joystick.joy1_TopHat == 0)
  {
    servo[servo1] = ServoValue[servo1] + caseyIsTall;
    servo[servo2] = ServoValue[servo2] + caseyIsTall;
  }
  else if(joystick.joy1_TopHat == 4)
  {
    servo[servo1] = ServoValue[servo1] - caseyIsTall;
    servo[servo2] = ServoValue[servo2] - caseyIsTall;
  }
  */

  if(joystick.joy1_TopHat == 2)
  {
    servo[servo3] = ServoValue[servo3] + caseyIsTall;
    servo[servo4] = ServoValue[servo4] - caseyIsTall;
  }
  else if(joystick.joy1_TopHat == 6)
  {
    servo[servo3] = ServoValue[servo3] - caseyIsTall;
    servo[servo4] = ServoValue[servo4] + caseyIsTall;
  }

  if(joy1Btn(7) == 1)
    servo[servo5] = ServoValue[servo5] - caseyIsTall;
  else if(joy1Btn(5) == 1)
    servo[servo5] = ServoValue[servo5] + caseyIsTall;

  /*if( (joy1Btn(6) == 1) && (continuousRotationLeft > 50) )
  {
      continuousRotationLeft = continuousRotationLeft+10;
      servo[servo6] =  continuousRotationLeft;
  }
  else if( (joy1Btn(8) == 1) && (continuousRotationLeft < 170) )
  {
      continuousRotationLeft = continuousRotationLeft-10;
      servo[servo6] = continuousRotationLeft;
  }*/

  /*
  if (joy1Btn(6) == 1)
    servo[servo6] = alexLikesMenRoof;
  else if (joy1Btn(8) == 1)
    servo[servo6] = alexLikesMenFloor;
  else
    servo[servo6] = 127;
  */

  //lego motor servos
  if(joy1Btn(1) == 1)
    motor[nxtMotorA] = 50;
  else if(joy1Btn(3) == 1)
    motor[nxtMotorA] = -50;
  else
    motor[nxtMotorA] = 0;

  /*
  if(joy1Btn(2) == 1)
    motor[nxtMotorB] = -50;
  else if(joy1Btn(4) == 1)
    motor[nxtMotorB] = 50;
  else
    motor[nxtMotorB] = 0;
  */
}

void TakeOnMe()
{
  //        160 = Tempo
  //          4 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  587,   17); wait1Msec( 188);  // Note(D5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  493,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(  830,   17); wait1Msec( 188);  // Note(G#5, Duration(Eighth))
  PlayTone(  830,   17); wait1Msec( 188);  // Note(G#5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  587,   17); wait1Msec( 188);  // Note(D5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  587,   17); wait1Msec( 188);  // Note(D5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  493,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(  830,   17); wait1Msec( 188);  // Note(G#5, Duration(Eighth))
  PlayTone(  830,   17); wait1Msec( 188);  // Note(G#5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  587,   17); wait1Msec( 188);  // Note(D5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  739,   17); wait1Msec( 188);  // Note(F#5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  PlayTone(  659,   17); wait1Msec( 188);  // Note(E5, Duration(Eighth))
  return;
}

task main()
{
  //finding null point
  /* for (int i = 0; i < 255; i++)
  {
    servo[servo6] = i;
    wait10Msec(10);
  } */
  //TakeOnMe();
  while (true)
  {
    TeleOp();
  }
}
