// Created by Christopher Su
// Catalyst Robotics 2012-2013 Season

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     touchMuxer,     sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motor12,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motor11,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorArm,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     motor21,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     motor22,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")

#include "JoystickDriver.c"
#include "../Headers/CSEnumerated.h"
#include "../Headers/CSMethods.h"

void initializeRobot() { return; }

task main() {
  initializeRobot();
  waitForStart(); // Wait for the beginning of autonomous phase.

  //wait10Msec(1500);

	//ArmUpDistance(2);
	/*
	while (true) {
		writeDebugStreamLine("Sensor: %d", SensorValue(IRseeker));
	}
	*/

	//holonomicEncodedForward(100, 4.8); //each revolution moves 6.5 inches, was 6.780523077
	holonomicEncodedForward(100, 5);
	wait10Msec(50);
	holonomicEncodedSpinRight(100, 0.775);
	//wait10Msec(1000);

	//ArmUpDistance(8.5);
	/*
	while (SensorValue(IRseeker) != autonomousIRseekerTarget) {
		writeDebugStreamLine("Sensor: %d", SensorValue(IRseeker));
		if (SensorValue(IRseeker) == 0) {
			MotorS(motor12);
			MotorS(motor22);
			MotorS(motor11);
			MotorS(motor21);
		}
		else if (SensorValue(IRseeker) < autonomousIRseekerTarget) {
			holonomicEncodedStrafe(-25, 0.1);
			wait10Msec(10);
		}
		else if (SensorValue(IRseeker) > autonomousIRseekerTarget) {
			holonomicEncodedStrafe(25, 0.1);
			wait10Msec(10);
		}
	}
	*/
  ArmUp();
  wait10Msec(100);
  holonomicEncodedForward(100,1.55); // was 75
  wait10Msec(100);
  ArmDownDistance(2);
  wait10Msec(100);
  holonomicEncodedForward(-100,3);
  //specifyTwoMotorsForDistance(motor11, motor21, 100, 3);
  wait10Msec(100);
  ArmDown();

  /*while(true){
  	for(int i = 0; i<250; i=i+25) {
 	 servo[servo1] = i;
 	 wait10Msec(100);
 }*/
}
