// Created by Christopher Su
// Catalyst Robotics 2012-2013 Season

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     touchMuxer,     sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motor12,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motor11,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorArm,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     motor21,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     motor22,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// #pragma DebuggerWindows("debugStream")

#include "JoystickDriver.c"
#include "../Headers/CSEnumerated.h"
#include "../Headers/CSMethods.h"

void initializeRobot() { return; }

void processWheels() {

	/*
	if (Button(CONTROLLER_A, 2) && Button(CONTROLLER_A, 8))
		controllerAMultiplier = -0.5;
	else if (Button(CONTROLLER_A, 8) && !Button(CONTROLLER_A, 2))
		controllerAMultiplier = -1;
	else if (Button(CONTROLLER_A, 2) && !Button(CONTROLLER_A, 8))
		controllerAMultiplier = 0.5;
	else
		controllerAMultiplier = 1;
	*/

	if (Button(CONTROLLER_A, 8))
		controllerAMultiplier = -1;
	else
		controllerAMultiplier = 1;
/*
	if ((Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) > 15) && (Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) < 100)) {
		motorSpeedFixMultiplier12 = 0.05;
		motorSpeedFixMultiplier22 = 0.05;
	}
	else if ((Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) < -15) && (Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) > -100)) {
		motorSpeedFixMultiplier12 = 0.05;
		motorSpeedFixMultiplier22 = 0.05;
	}
	else {
		motorSpeedFixMultiplier11 = 1;
		motorSpeedFixMultiplier12 = 1;
		motorSpeedFixMultiplier21 = 1;
		motorSpeedFixMultiplier22 = 1;
	}
*/
	if (((Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X) > 15) || (Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X) < -15)) && !Button(CONTROLLER_A, 7)) {
		MotorF(motor12, Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier*motorSpeedFixMultiplier12);
		MotorF(motor22, Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier*motorSpeedFixMultiplier22);
		MotorF(motor11, Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier*motorSpeedFixMultiplier11);
		MotorF(motor21, Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier*motorSpeedFixMultiplier21);
	}
	else if ((Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) > 15) || (Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y) < -15)) {
		MotorF(motor12, Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y)*controllerAMultiplier*motorSpeedFixMultiplier12);
		MotorF(motor22, Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y)*controllerAMultiplier*motorSpeedFixMultiplier22);
		MotorF(motor11, -Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y)*controllerAMultiplier*motorSpeedFixMultiplier11);
		MotorF(motor21, -Happy(CONTROLLER_A, JOYSTICK_R, AXIS_Y)*controllerAMultiplier*motorSpeedFixMultiplier21);
	}
	else if (!Button(CONTROLLER_A, 5) && !Button(CONTROLLER_A, 6) && (Hat(CONTROLLER_A) == HAT_NONE)) {
		MotorS(motor12);
		MotorS(motor22);
		MotorS(motor11);
		MotorS(motor21);
	}

	if (Button(CONTROLLER_A, 3))
		specifyTwoMotorsForDistance(motor11, motor21, 25, 0.01);
	else if (Button(CONTROLLER_A, 1))
		specifyTwoMotorsForDistance(motor11, motor21, -25, 0.01);

	if (Hat(CONTROLLER_A) == HAT_NE) {
		MotorF(motor12, 90*controllerAMultiplier);
		MotorF(motor22, 90*controllerAMultiplier);
	}
	else if (Hat(CONTROLLER_A) == HAT_NW) {
		MotorF(motor11, -90*controllerAMultiplier);
		MotorF(motor21, -90*controllerAMultiplier);
	}
	else if (Hat(CONTROLLER_A) == HAT_SW) {
		MotorF(motor12, -90*controllerAMultiplier);
		MotorF(motor22, -90*controllerAMultiplier);
	}
	else if (Hat(CONTROLLER_A) == HAT_SE) {
		MotorF(motor11, 90*controllerAMultiplier);
		MotorF(motor21, 90*controllerAMultiplier);
	}

	if(Button(CONTROLLER_A, 5)) {
		if (controllerAMultiplier == -1)
			spinLeft();
		else
			spinRight();
	}
	else if(Button(CONTROLLER_A, 6)) {
		if (controllerAMultiplier == -1)
			spinRight();
		else
			spinLeft();
	}

	if(Button(CONTROLLER_A, 5))
			spinRight();
	else if(Button(CONTROLLER_A, 6))
			spinLeft();

	//writeDebugStreamLine("12: %d, 22: %d", (Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier*motorSpeedFixMultiplier12), (Happy(CONTROLLER_A, JOYSTICK_L, AXIS_X)*controllerAMultiplier*motorSpeedFixMultiplier22));
}

void processArm() {
	if ((Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y) > 15) || (Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y) < -15)) {
		if(!touchMuxer1 && !touchMuxer2)
			MotorF(motorArm, Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2);
		else if (!touchMuxer1 && (Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2 < 0))
			MotorF(motorArm, Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2);
		else if (!touchMuxer2 && (Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2 > 0))
			MotorF(motorArm, Happy(CONTROLLER_B, JOYSTICK_R, AXIS_Y)*2);
		else if (!touchMuxer1 || !touchMuxer2)
			MotorS(motorArm);
	}
	else
		MotorS(motorArm);

	if (Button(CONTROLLER_B, 4))
		ArmUpDistance(0.25);
	else if (Button(CONTROLLER_B, 2))
		ArmDownDistance(0.25);
}

void processServos() {

	//if ((Happy(CONTROLLER_B, JOYSTICK_L, AXIS_Y) > 10) || (Happy(CONTROLLER_B, JOYSTICK_L, AXIS_Y) < -10)) {
	/*
	servo[servo1] = 90;
	servo[servo2] = 90;
	servo[servo3] = 90;
	*/
	//}
	/*
	if(Button(CONTROLLER_A, 2)) {
	servo[servo1] += 1;,
	}
	else if(Button(CONTROLLER_A, 4)) {
	servo[servo1] += -1;
	}
	*/
}

void processSensors() {
	touchMultiplexerUpdate();
}

task main() {
	initializeRobot();
	for (int i=0; ; i++) {
		CatsAndCorgis();
		processSensors();
		processWheels();
		processArm();
		//processServos();
	}
}
